FROM eclipse-temurin:23-jdk

# Set working directory
WORKDIR /app

# Copy necessary files
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

# Set build-time environment variables
ARG SPRING_AI_API_KEY
ARG SPRING_AI_COMPLETION_URL
ARG SPRING_AI_BASE_URL
ARG RAILWAY_DATABASE_URL
ARG RAILWAY_DATABASE_USERNAME
ARG RAILWAY_DATABASE_PASSWORD
ARG ALLOWED_ORIGINS
ARG AUTH_ISSUER_URI
ARG AUTH_JWK_SET_URI

# Package the application 
RUN ./mvnw package -DskipTests

# Copy the JAR file into the container 
COPY target/*.jar app.jar

# Set runtime environment variables
ENV SPRING_AI_API_KEY=${SPRING_AI_API_KEY}
ENV SPRING_AI_COMPLETION_URL=${SPRING_AI_COMPLETION_URL}
ENV SPRING_AI_BASE_URL=${SPRING_AI_BASE_URL}
ENV RAILWAY_DATABASE_URL=${RAILWAY_DATABASE_URL}
ENV RAILWAY_DATABASE_USERNAME=${RAILWAY_DATABASE_USERNAME}
ENV RAILWAY_DATABASE_PASSWORD=${RAILWAY_DATABASE_PASSWORD}
ENV ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
ENV AUTH_ISSUER_URI=${AUTH_ISSUER_URI}
ENV AUTH_JWK_SET_URI=${AUTH_JWK_SET_URI}

# Expose port for application
EXPOSE 8080

# Entry point to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
