name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: 'r-checker-454418' 
  REGION: 'europe-central2' 
  SERVICE: 'resume-chcker'        
  IMAGE_NAME: 'resume-checker-service'
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WIF }} 

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: ${{ secrets.GCP_EMAIL }}
        
      # BEGIN - Docker auth and build
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build --tag "$DOCKER_TAG" \
            --build-arg SPRING_AI_API_KEY=${{ secrets.SPRING_AI_API_KEY }} \
            --build-arg SPRING_AI_COMPLETION_URL=${{ secrets.SPRING_AI_COMPLETION_URL }} \
            --build-arg SPRING_AI_BASE_URL=${{ secrets.SPRING_AI_BASE_URL }} \
            --build-arg RAILWAY_DATABASE_URL=${{ secrets.RAILWAY_DATABASE_URL }} \
            --build-arg RAILWAY_DATABASE_USERNAME=${{ secrets.RAILWAY_DATABASE_USERNAME }} \
            --build-arg RAILWAY_DATABASE_PASSWORD=${{ secrets.RAILWAY_DATABASE_PASSWORD }} \
            --build-arg ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} \
            --build-arg AUTH_ISSUER_URI=${{ secrets.AUTH_ISSUER_URI }} \
            --build-arg AUTH_JWK_SET_URI=${{ secrets.AUTH_JWK_SET_URI }} .
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ env.REGION }}-docker.pkg.dev
          docker push "$DOCKER_TAG"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.IMAGE_NAME }}' 
          region: '${{ env.REGION }}'
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}
