name: Deploy to Cloud Run from Artifact Registry

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: 'r-checker-454418'
  REGION: 'europe-central2'  
  SERVICE: 'resume-checker-service'  
  ARTIFACT_REGISTRY_REPO: 'resume-chcker'  
  ARTIFACT_REGISTRY_REGION: 'europe-central2'  

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v4'

      - id: 'Auth_to_GC'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF }}
          service_account: ${{ secrets.GCP_EMAIL }}

      - name: 'Set up Docker Build'
        run: |
          echo "Building Docker image..."
          docker build \
            --build-arg SPRING_AI_API_KEY=${{ secrets.SPRING_AI_API_KEY }} \
            --build-arg SPRING_AI_COMPLETION_URL=${{ secrets.SPRING_AI_COMPLETION_URL }} \
            --build-arg SPRING_AI_BASE_URL=${{ secrets.SPRING_AI_BASE_URL }} \
            --build-arg RAILWAY_DATABASE_URL=${{ secrets.RAILWAY_DATABASE_URL }} \
            --build-arg RAILWAY_DATABASE_USERNAME=${{ secrets.RAILWAY_DATABASE_USERNAME }} \
            --build-arg RAILWAY_DATABASE_PASSWORD=${{ secrets.RAILWAY_DATABASE_PASSWORD }} \
            --build-arg ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} \
            --build-arg AUTH_ISSUER_URI=${{ secrets.AUTH_ISSUER_URI }} \
            --build-arg AUTH_JWK_SET_URI=${{ secrets.AUTH_JWK_SET_URI }} \
            -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REGISTRY_REPO}/${SERVICE}:latest .

      - name: 'Push Docker Image to Artifact Registry'
        run: |
          echo "Pushing Docker image to Artifact Registry..."
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REGISTRY_REPO}/${SERVICE}:latest

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REGISTRY_REPO}/${SERVICE}:latest'
          secrets: |-
            SPRING_AI_API_KEY=${{ secrets.SPRING_AI_API_KEY }}
            SPRING_AI_COMPLETION_URL=${{ secrets.SPRING_AI_COMPLETION_URL }}
            SPRING_AI_BASE_URL=${{ secrets.SPRING_AI_BASE_URL }}
            RAILWAY_DATABASE_URL=${{ secrets.RAILWAY_DATABASE_URL }}
            RAILWAY_DATABASE_USERNAME=${{ secrets.RAILWAY_DATABASE_USERNAME }}
            RAILWAY_DATABASE_PASSWORD=${{ secrets.RAILWAY_DATABASE_PASSWORD }}
            ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
            AUTH_ISSUER_URI=${{ secrets.AUTH_ISSUER_URI }}
            AUTH_JWK_SET_URI=${{ secrets.AUTH_JWK_SET_URI }}

      - name: 'Show Cloud Run URL'
        run: |
          echo "Cloud Run URL: ${{ steps.deploy.outputs.url }}"
