name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: 'r-checker-454418'
  REGION: 'europe-central2'
  SERVICE: 'resume-checker'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' 
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF }}
          service_account: ${{secrets.GCP_EMAIL}}
          
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' 
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          # NOTE: If using a different source folder, update the image name below:
          source: './'
          env-vars: |
              SPRING_AI_API_KEY=${{ secrets.SPRING_AI_API_KEY }}
              SPRING_AI_COMPLETION_URL=${{ secrets.SPRING_AI_COMPLETION_URL }}
              SPRING_AI_BASE_URL=${{ secrets.SPRING_AI_BASE_URL }}
              RAILWAY_DATABASE_URL=${{ secrets.RAILWAY_DATABASE_URL }}
              RAILWAY_DATABASE_USERNAME=${{ secrets.RAILWAY_DATABASE_USERNAME }}
              RAILWAY_DATABASE_PASSWORD=${{ secrets.RAILWAY_DATABASE_PASSWORD }}
              ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
              AUTH_ISSUER_URI=${{ secrets.AUTH_ISSUER_URI }}
              AUTH_JWK_SET_URI=${{ secrets.AUTH_JWK_SET_URI }}

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
